# fly.toml app configuration file generated for good on 2024-02-03T21:13:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "good"
primary_region = "lhr"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]
  [build.args]
    BP_GO_BUILD_IMPORT_PATH = "github.com/wr125/fullstack/views"
    BP_KEEP_FILES = "assets/*:"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
